-- Endurecimiento de consistencia, seguridad e historial.
-- Ejecutar después de 20260921-normalizacion-integridad.sql.
BEGIN;

CREATE TABLE IF NOT EXISTS schema_migrations (
  nombre varchar(255) PRIMARY KEY,
  aplicada_at timestamptz NOT NULL DEFAULT now()
);

CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Elimina exclusivamente las 20 cuentas de demostración identificadas.
-- Se retiran también sus restaurantes y reservas relacionadas para no dejar huérfanos.
CREATE TEMP TABLE usuarios_demo_a_eliminar ON COMMIT DROP AS
SELECT id_usuario
FROM usuarios
WHERE lower(correo) ~ '^restaurante([1-9]|1[0-9]|20)@mesachapaca\.com$';

CREATE TEMP TABLE restaurantes_demo_a_eliminar ON COMMIT DROP AS
SELECT r.id_restaurante
FROM restaurante r
WHERE EXISTS (
  SELECT 1
  FROM solicitud s
  JOIN usuarios_demo_a_eliminar u ON u.id_usuario = s.id_usuario
  WHERE s.id_solicitud = r.id_solicitud
)
OR EXISTS (
  SELECT 1
  FROM usuarios u
  JOIN usuarios_demo_a_eliminar objetivo ON objetivo.id_usuario = u.id_usuario
  WHERE lower(u.correo) = lower(r.correo)
);

DELETE FROM reservas
WHERE id_usuario IN (SELECT id_usuario FROM usuarios_demo_a_eliminar)
   OR id_mesa IN (
     SELECT m.id_mesa
     FROM mesa m
     JOIN restaurantes_demo_a_eliminar r USING (id_restaurante)
   );
DELETE FROM respuesta_resena
WHERE id_usuario_restaurante IN (
  SELECT id_usuario FROM usuarios_demo_a_eliminar
);
DELETE FROM restaurante
WHERE id_restaurante IN (SELECT id_restaurante FROM restaurantes_demo_a_eliminar);
DELETE FROM usuarios
WHERE id_usuario IN (SELECT id_usuario FROM usuarios_demo_a_eliminar);

-- Correos canónicos también ante escrituras directas a PostgreSQL.
UPDATE usuarios SET correo = lower(btrim(correo));
ALTER TABLE usuarios DROP CONSTRAINT IF EXISTS usuarios_correo_key;
CREATE UNIQUE INDEX uq_usuarios_correo_normalizado ON usuarios (lower(correo));

-- Borrado lógico para conservar trazabilidad de usuarios y restaurantes reales.
ALTER TABLE usuarios ADD COLUMN eliminado_at timestamptz;
ALTER TABLE usuarios ADD COLUMN actualizado_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE restaurante ADD COLUMN eliminado_at timestamptz;
ALTER TABLE restaurante ADD COLUMN actualizado_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE restaurante
  ADD COLUMN zona_horaria varchar(64) NOT NULL DEFAULT 'America/La_Paz';
CREATE INDEX ix_usuarios_activos ON usuarios (id_usuario) WHERE eliminado_at IS NULL;
CREATE INDEX ix_restaurantes_activos ON restaurante (id_restaurante) WHERE eliminado_at IS NULL;

-- Una relación estable de propietarios y personal, independiente de la solicitud inicial.
CREATE TABLE usuario_restaurante (
  id_usuario integer NOT NULL REFERENCES usuarios(id_usuario) ON DELETE CASCADE,
  id_restaurante integer NOT NULL REFERENCES restaurante(id_restaurante) ON DELETE CASCADE,
  rol varchar(20) NOT NULL DEFAULT 'propietario',
  activo boolean NOT NULL DEFAULT true,
  fecha_asignacion timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT usuario_restaurante_pkey PRIMARY KEY (id_usuario, id_restaurante),
  CONSTRAINT ck_usuario_restaurante_rol
    CHECK (rol IN ('propietario', 'administrador', 'empleado'))
);
INSERT INTO usuario_restaurante (id_usuario, id_restaurante, rol)
SELECT s.id_usuario, r.id_restaurante, 'propietario'
FROM restaurante r
JOIN solicitud s ON s.id_solicitud = r.id_solicitud
WHERE s.estado = 'aprobada'
ON CONFLICT DO NOTHING;
CREATE INDEX ix_usuario_restaurante_restaurante
  ON usuario_restaurante (id_restaurante) WHERE activo;

-- Capacidad siempre conocida y válida.
UPDATE mesa m
SET capacidad = GREATEST(
  1,
  COALESCE((SELECT max(r.numero_personas) FROM reservas r WHERE r.id_mesa = m.id_mesa), 1)
)
WHERE capacidad IS NULL;
ALTER TABLE mesa ALTER COLUMN capacidad SET NOT NULL;

-- Horarios válidos y sin franjas superpuestas para un mismo día.
ALTER TABLE horario_atencion
  ADD CONSTRAINT ck_horario_orden CHECK (hora_inicio < hora_fin),
  ADD CONSTRAINT ex_horario_sin_solapamiento
    EXCLUDE USING gist (
      id_restaurante WITH =,
      dia_semana WITH =,
      tsrange(
        DATE '2000-01-03' + hora_inicio,
        DATE '2000-01-03' + hora_fin,
        '[)'
      ) WITH &&
    );

-- Excepciones para cierres, feriados y horarios especiales.
CREATE TABLE excepcion_horario (
  id_excepcion integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_restaurante integer NOT NULL REFERENCES restaurante(id_restaurante) ON DELETE CASCADE,
  fecha date NOT NULL,
  cerrado boolean NOT NULL DEFAULT true,
  hora_inicio time,
  hora_fin time,
  motivo varchar(255),
  CONSTRAINT uq_excepcion_restaurante_fecha UNIQUE (id_restaurante, fecha),
  CONSTRAINT ck_excepcion_horas CHECK (
    (cerrado AND hora_inicio IS NULL AND hora_fin IS NULL)
    OR
    (NOT cerrado AND hora_inicio IS NOT NULL AND hora_fin IS NOT NULL AND hora_inicio < hora_fin)
  )
);
CREATE INDEX ix_excepcion_fecha ON excepcion_horario (fecha, id_restaurante);

-- Reservas por intervalos: evita cruces, no solo horas exactamente iguales.
ALTER TABLE reservas ADD COLUMN duracion_minutos integer NOT NULL DEFAULT 120;
ALTER TABLE reservas ADD COLUMN actualizado_at timestamptz NOT NULL DEFAULT now();
ALTER TABLE reservas
  ADD CONSTRAINT ck_reserva_duracion CHECK (duracion_minutos BETWEEN 15 AND 480);
DROP INDEX IF EXISTS uq_reserva_mesa_horario_activa;
ALTER TABLE reservas
  ADD CONSTRAINT ex_reserva_mesa_intervalo_activo
    EXCLUDE USING gist (
      id_mesa WITH =,
      tsrange(
        fecha + hora,
        fecha + hora + (duracion_minutos * INTERVAL '1 minute'),
        '[)'
      ) WITH &&
    )
    WHERE (estado IN ('pendiente', 'confirmada'));

-- Una reseña nueva exige una visita comprobable; las reseñas antiguas quedan como legado.
ALTER TABLE resenas ADD COLUMN id_reserva integer;
ALTER TABLE resenas
  ADD CONSTRAINT fk_resena_reserva
    FOREIGN KEY (id_reserva) REFERENCES reservas(id_reserva) ON DELETE SET NULL;
CREATE UNIQUE INDEX uq_resena_reserva
  ON resenas (id_reserva) WHERE id_reserva IS NOT NULL;

-- Los tokens utilizables nunca quedan recuperables desde un volcado de la BD.
UPDATE invitacion_token
SET usado = true
WHERE tipo = 'recuperacion'
  AND token !~ '^[0-9a-f]{64}$';
UPDATE invitacion_token
SET token = encode(digest(token, 'sha256'), 'hex')
WHERE tipo = 'invitacion';
DELETE FROM invitacion_token
WHERE usado OR fecha_expiracion <= now();
ALTER TABLE invitacion_token
  ADD CONSTRAINT ck_token_tipo CHECK (tipo IN ('invitacion', 'recuperacion')),
  ADD CONSTRAINT ck_token_hash CHECK (token ~ '^[0-9a-f]{64}$');

-- Auditoría persistente sin cuerpos, correos, PIN, cabeceras ni tokens.
CREATE TABLE auditoria_evento (
  id_evento bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_usuario integer REFERENCES usuarios(id_usuario) ON DELETE SET NULL,
  accion varchar(10) NOT NULL,
  ruta varchar(255) NOT NULL,
  id_recurso varchar(100),
  resultado varchar(20) NOT NULL,
  codigo_estado integer NOT NULL,
  fecha timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT ck_auditoria_accion CHECK (accion IN ('POST', 'PUT', 'PATCH', 'DELETE')),
  CONSTRAINT ck_auditoria_resultado CHECK (resultado IN ('success', 'failure')),
  CONSTRAINT ck_auditoria_codigo CHECK (codigo_estado BETWEEN 100 AND 599)
);
CREATE INDEX ix_auditoria_usuario_fecha ON auditoria_evento (id_usuario, fecha DESC);
CREATE INDEX ix_auditoria_fecha ON auditoria_evento (fecha DESC);

-- Evita que cualquier rol pueda crear objetos en el esquema público.
REVOKE CREATE ON SCHEMA public FROM PUBLIC;

INSERT INTO schema_migrations (nombre)
VALUES ('20260922-consistencia-seguridad.sql')
ON CONFLICT DO NOTHING;

COMMIT;
