// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuA_SOWQcgDX8oJmS-0lBAH6XDzEz0-Zk',
    appId: '1:896002873995:web:6cdaa38960160e76d9128e',
    messagingSenderId: '896002873995',
    projectId: 'resttarija',
    authDomain: 'resttarija.firebaseapp.com',
    storageBucket: 'resttarija.firebasestorage.app',
    measurementId: 'G-8JV281JYH5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9ypnPkO2i6To2KD7IHnloUsRLEnO4llE',
    appId: '1:896002873995:android:8f51346c61ac7428d9128e',
    messagingSenderId: '896002873995',
    projectId: 'resttarija',
    storageBucket: 'resttarija.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_FkAg8YQkIfQv3v2_YWIVliz6JE1vVdg',
    appId: '1:896002873995:ios:abe9b65cc93644b4d9128e',
    messagingSenderId: '896002873995',
    projectId: 'resttarija',
    storageBucket: 'resttarija.firebasestorage.app',
    iosClientId: '896002873995-jtdvcf6jq804hrii1a1urketb9m671pb.apps.googleusercontent.com',
    iosBundleId: 'com.proyecto.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuA_SOWQcgDX8oJmS-0lBAH6XDzEz0-Zk',
    appId: '1:896002873995:web:eb9a346698b74ea0d9128e',
    messagingSenderId: '896002873995',
    projectId: 'resttarija',
    authDomain: 'resttarija.firebaseapp.com',
    storageBucket: 'resttarija.firebasestorage.app',
    measurementId: 'G-RMG90L5Y2V',
  );
}
